name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: draw image 
      run: cargo run --release > image.ppm
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: image.ppm
        path: image.ppm
      
